## Ini Heading

Ini untuk menjelaskan apa itu cell

$Y_i = \sum^{J}_{i =1}(c-1)^2$

In [55]:
# Belajar numpy 
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
# membuat array pakai arange

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
arr = np.arange(1,11)

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[7]

8

In [10]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[[1,3,4,5, 7]] = 100

In [12]:
arr[[1,3,4,5]]

array([100, 100, 100, 100])

In [13]:
arr

array([  1, 100,   3, 100, 100, 100,   7, 100,   9,  10])

In [14]:
slice_of_arr = arr[1:5]

In [15]:
slice_of_arr[:] = 0

In [16]:
slice_of_arr

array([0, 0, 0, 0])

In [17]:
arr

array([  1,   0,   0,   0,   0, 100,   7, 100,   9,  10])

In [18]:
array_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])


In [19]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
array_2d[1]

array([20, 25, 30])

In [21]:
array_2d[1][0]

20

In [22]:
array_2d[1,0]

20

In [23]:
array_2d.shape

(3, 3)

## Untuk Array 2D

di posisi 0 adalah Row, dan posisi 1 adalah kolom

In [24]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [27]:
np.random.seed(101)

In [32]:
np.random.rand(2)

array([0.87758732, 0.94926413])

In [29]:
np.random.rand(5,5)

array([[0.02847423, 0.17152166, 0.68527698, 0.83389686, 0.30696622],
       [0.89361308, 0.72154386, 0.18993895, 0.55422759, 0.35213195],
       [0.1818924 , 0.78560176, 0.96548322, 0.23235366, 0.08356143],
       [0.60354842, 0.72899276, 0.27623883, 0.68530633, 0.51786747],
       [0.04848454, 0.13786924, 0.18696743, 0.9943179 , 0.5206654 ]])

In [30]:
np.random.randn(2)

array([1.58917569, 0.53322084])

In [31]:
#mean = 0, std = 1. Sampel disini adalah Z-score
np.random.randn(5,5)

array([[ 8.57349240e-01,  8.70763251e-02, -3.97461714e-01,
         1.26168798e+00,  4.33331317e-01],
       [-1.36613700e-01,  8.82139838e-01, -3.77811241e-01,
         1.46638797e-01,  1.26912178e+00],
       [ 3.07881084e-01, -6.06805545e-01,  9.19318419e-01,
        -1.19611840e+00,  5.08945217e-01],
       [-8.48439962e-01,  2.01079346e+00, -1.37609705e-01,
        -5.98269227e-01,  2.82337430e-02],
       [ 3.92746078e-01, -1.44169525e+00,  3.22839962e-04,
        -1.04991168e+00, -2.29937498e-01]])

In [42]:
np.random.randint(1,4)

2

In [47]:
np.random.randint(1,4,100)

array([1, 3, 1, 3, 2, 3, 3, 1, 1, 2, 3, 2, 2, 1, 1, 3, 2, 3, 3, 3, 3, 3,
       1, 2, 1, 1, 3, 1, 1, 3, 2, 3, 2, 1, 3, 1, 1, 2, 1, 2, 2, 1, 1, 3,
       2, 2, 3, 3, 2, 2, 3, 2, 2, 1, 2, 1, 1, 3, 2, 3, 1, 2, 3, 1, 3, 3,
       1, 2, 1, 1, 3, 3, 1, 2, 3, 3, 1, 1, 2, 1, 1, 2, 1, 1, 2, 3, 3, 2,
       1, 2, 2, 2, 2, 2, 1, 1, 3, 2, 3, 2])

In [48]:
arr =np.arange(25)
ranarr = np.random.randint(0,50,10)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr

array([36, 43, 27,  2,  3,  6, 41,  3,  8, 24])

In [51]:
ranarr.min()

2

In [52]:
ranarr.max()

43

In [53]:
ranarr.argmin()

3

In [54]:
ranarr.argmax()

1

In [62]:
np.median(ranarr)

16.0

In [56]:
ranarr.mean()

19.3

In [59]:
ranarr.std()

15.9

In [64]:
np.array([1,2, 'test', True])

array(['1', '2', 'test', 'True'], dtype='<U11')

In [66]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
for i in range(10):
    arr2d[i] = i
arr2d    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [72]:
arr2d[[1,3,4,6,6]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [80]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
bool_arr = arr>4

In [77]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [78]:
#Selection of array
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
arr[(arr > 2) & (arr < 7) | (arr == 1)]

array([1, 3, 4, 5, 6])

In [93]:
arr = np.arange(10)
arr1 = np.arange(5)

In [95]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
1/arr

C:\Users\MSI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [97]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [100]:
np.log2(100)

6.643856189774724