In [1]:
import numpy as np

# Soal 1

In [2]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Output

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

## Soal 2

In [8]:
arr = np.arange(4,13).reshape(3,3)
arr

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Output

array([[ 5,  4,  6],
       [ 8,  7,  9],
       [11, 10, 12]])

## Soal 3

In [11]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Output

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## Soal 4

In [13]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

## Output

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])